# Generated by Django 5.2.8 on 2026-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Aadhar',
            new_name='aadhar',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=30),
        ),
    ]
