# Generated by Django 5.2.8 on 2026-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_aadhar_customer_aadhar_alter_customer_cust_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=20),
        ),
    ]
