# Generated by Django 5.2.8 on 2026-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_customer_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=30)),
                ('acc_no', models.CharField(max_length=30)),
                ('acc_holder', models.CharField(max_length=30)),
                ('cust_id', models.CharField(max_length=30)),
                ('acc_type', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
