# Generated by Django 5.2.8 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='created_at',
        ),
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
