# Generated by Django 5.2.8 on 2026-09-04 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_accounts_created_at_accounts_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
