# Generated by Django 4.2.30 on 2026-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_accounts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='pin',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
