# Generated by Django 4.2.30 on 2026-09-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_accounts_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='pin',
        ),
    ]
