# Generated by Django 4.2.30 on 2026-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_remove_accounts_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=10)),
                ('acc_no', models.CharField(max_length=30)),
                ('acc_name', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('current_balance', models.CharField(max_length=30)),
                ('balance_after', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
