# Generated by Django 5.2.17 on 2026-09-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
