# Generated by Django 5.2.17 on 2026-09-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_delete_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
