# Generated by Django 5.2.17 on 2026-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Othertransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
