# Generated by Django 5.2.17 on 2026-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_othertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertransactions',
            name='bank',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
