# Generated by Django 5.2.17 on 2026-09-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_othertransactions_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertransactions',
            name='transaction_amount',
        ),
    ]
