# Generated by Django 5.2.17 on 2026-09-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_remove_othertransactions_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Othertransactions',
        ),
    ]
