# Generated by Django 5.2.17 on 2026-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_othertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertransactions',
            name='transaction_amount',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
